### ISSUE TITLE
Keeps running indefinetly on both mac books

### ISSUE THREAD

**Issue by hellomegha** [artiebits/fake-git-history#7]
`fake-git-history --commitsPerDay "0,7" -s "19/10/22" -e "20/01/15"`

keeps running indefinitely on the both the macs, with no visibile changes in file in the git repository.
eventually I killed the process with Ctrl + C and got this error in the screenshot 

```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at normalizeSpawnArguments (child_process.js:409:11)
    at spawn (child_process.js:546:13)
    at Object.execFile (child_process.js:232:17)
    at exec (child_process.js:153:25)
    at child_process.js:167:29
    at generateHistory (/Users/*****/.config/yarn/global/node_modules/fake-git-history/index.js:42:11)
    at module.exports (/Users/*****/.config/yarn/global/node_modules/fake-git-history/index.js:58:5)
    at Object.<anonymous> (/Users/*****/.config/yarn/global/node_modules/fake-git-history/cli.js:48:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
```
**Screenshots**

![image](https://user-images.githubusercontent.com/62517966/88138737-1fb0a700-cba3-11ea-8284-cbf5e4ab3754.png)

after killing the process doing the `git log` shows nothing

This behavior is reproducible on both my macs

**Comment by artiebits** [comment]
Hi! I am sorry, I made a mistake in documentation saying the date must be in `YY/MM/DD` format. The date format must be `YYY/MM/DD`. So, the correct command for your is `fake-git-history --commitsPerDay "0,7" -s "2019/10/22" -e "2020/01/15"`

**Comment by hellomegha** [comment]
Thanks, It does I can create a PR shortly to update the documentation.

**Comment by artiebits** [comment]
that would be nice, thank you 👍

**Comment by artiebits** [comment]
let me know if you have any questions about opening a PR
